"""Export reports in multiple formats (Markdown, PDF, DOCX, JSON)"""

from pathlib import Path
from typing import Optional, BinaryIO
from io import BytesIO
import json
import logging
from datetime import datetime
from enum import Enum

logger = logging.getLogger(__name__)


class ExportFormat(str, Enum):
    """Supported export formats"""
    MARKDOWN = "markdown"
    PDF = "pdf"
    JSON = "json"
    HTML = "html"


class ReportExporter:
    """Export reports in various formats"""
    
    def __init__(self):
        """Initialize exporter"""
        self.exports_dir = Path("exports")
        self.exports_dir.mkdir(exist_ok=True)
    
    def export_markdown(
        self,
        markdown_content: str,
        filename: str,
        output_dir: Optional[Path] = None
    ) -> Path:
        """Export as markdown file"""
        output_dir = output_dir or self.exports_dir
        output_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = output_dir / f"{filename}.md"
        filepath.write_text(markdown_content, encoding='utf-8')
        logger.info(f"Exported markdown to {filepath}")
        return filepath
    
    def export_pdf(
        self,
        markdown_content: str,
        filename: str,
        output_dir: Optional[Path] = None
    ) -> Path:
        """Export as PDF file"""
        from utils import markdown_to_pdf
        
        output_dir = output_dir or self.exports_dir
        output_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = output_dir / f"{filename}.pdf"
        
        # Extract title from markdown
        lines = markdown_content.split('\n')
        title = lines[0].replace('#', '').strip() if lines else "Report"
        
        pdf_buffer = markdown_to_pdf(markdown_content, title)
        filepath.write_bytes(pdf_buffer.getvalue())
        logger.info(f"Exported PDF to {filepath}")
        return filepath
    
    def export_html(
        self,
        markdown_content: str,
        filename: str,
        output_dir: Optional[Path] = None,
        include_styles: bool = True
    ) -> Path:
        """Export as HTML file"""
        import markdown as md
        from html import escape
        
        output_dir = output_dir or self.exports_dir
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Convert markdown to HTML
        html_content = md.markdown(markdown_content, extensions=['extra', 'toc'])
        
        # Wrap in HTML template
        if include_styles:
            html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{escape(filename)}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 900px;
            margin: 0 auto;
            padding: 20px;
            background-color: #f9f9f9;
        }}
        h1, h2, h3, h4, h5, h6 {{
            color: #1f4788;
            margin-top: 1.5em;
            margin-bottom: 0.5em;
        }}
        h1 {{
            border-bottom: 3px solid #1f4788;
            padding-bottom: 0.3em;
        }}
        code {{
            background-color: #f5f5f5;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
        }}
        pre {{
            background-color: #f5f5f5;
            padding: 12px;
            border-radius: 4px;
            overflow-x: auto;
        }}
        blockquote {{
            border-left: 4px solid #1f4788;
            margin: 0;
            padding-left: 16px;
            color: #666;
        }}
        table {{
            border-collapse: collapse;
            width: 100%;
            margin: 1em 0;
        }}
        th, td {{
            border: 1px solid #ddd;
            padding: 8px 12px;
            text-align: left;
        }}
        th {{
            background-color: #f5f5f5;
            font-weight: 600;
        }}
        .metadata {{
            color: #666;
            font-size: 0.9em;
            margin-bottom: 2em;
            padding-bottom: 1em;
            border-bottom: 1px solid #eee;
        }}
    </style>
</head>
<body>
    <div class="metadata">
        Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    </div>
    {html_content}
    <hr>
    <p style="text-align: center; color: #999; font-size: 0.9em;">
        Generated by Multi-Agent Research Assistant
    </p>
</body>
</html>"""
        else:
            html = html_content
        
        filepath = output_dir / f"{filename}.html"
        filepath.write_text(html, encoding='utf-8')
        logger.info(f"Exported HTML to {filepath}")
        return filepath
    
    def export_json(
        self,
        report_data: dict,
        filename: str,
        output_dir: Optional[Path] = None,
        pretty: bool = True
    ) -> Path:
        """Export as JSON file"""
        output_dir = output_dir or self.exports_dir
        output_dir.mkdir(parents=True, exist_ok=True)
        
        filepath = output_dir / f"{filename}.json"
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(
                report_data,
                f,
                indent=2 if pretty else None,
                default=str
            )
        
        logger.info(f"Exported JSON to {filepath}")
        return filepath
    
    def export_all(
        self,
        markdown_content: str,
        report_data: dict,
        filename: str,
        output_dir: Optional[Path] = None,
        formats: Optional[list] = None
    ) -> dict:
        """Export in multiple formats"""
        output_dir = output_dir or self.exports_dir
        formats = formats or [
            ExportFormat.MARKDOWN,
            ExportFormat.PDF,
            ExportFormat.HTML,
            ExportFormat.JSON
        ]
        
        results = {}
        
        if ExportFormat.MARKDOWN in formats:
            results['markdown'] = self.export_markdown(markdown_content, filename, output_dir)
        
        if ExportFormat.PDF in formats:
            try:
                results['pdf'] = self.export_pdf(markdown_content, filename, output_dir)
            except Exception as e:
                logger.error(f"PDF export failed: {e}")
        
        if ExportFormat.HTML in formats:
            try:
                results['html'] = self.export_html(markdown_content, filename, output_dir)
            except Exception as e:
                logger.error(f"HTML export failed: {e}")
        
        if ExportFormat.JSON in formats:
            results['json'] = self.export_json(report_data, filename, output_dir)
        
        return results


class ReportPackager:
    """Package reports for distribution"""
    
    @staticmethod
    def create_report_package(
        markdown_content: str,
        report_data: dict,
        package_name: str,
        output_dir: Optional[Path] = None
    ) -> Path:
        """Create a package with all report formats"""
        import zipfile
        
        output_dir = output_dir or Path("packages")
        output_dir.mkdir(parents=True, exist_ok=True)
        
        # Create temporary export directory
        temp_dir = output_dir / f"temp_{package_name}"
        temp_dir.mkdir(exist_ok=True)
        
        # Export all formats
        exporter = ReportExporter()
        exporter.export_all(
            markdown_content,
            report_data,
            package_name,
            temp_dir
        )
        
        # Create ZIP package
        package_path = output_dir / f"{package_name}.zip"
        
        with zipfile.ZipFile(package_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for file in temp_dir.glob("*"):
                zipf.write(file, arcname=file.name)
            
            # Add metadata
            metadata = {
                'package_name': package_name,
                'created_at': datetime.now().isoformat(),
                'formats': ['markdown', 'pdf', 'html', 'json'],
                'files': [f.name for f in temp_dir.glob("*")]
            }
            zipf.writestr(
                'METADATA.json',
                json.dumps(metadata, indent=2)
            )
        
        # Cleanup temp directory
        import shutil
        shutil.rmtree(temp_dir)
        
        logger.info(f"Created report package: {package_path}")
        return package_path


# Global exporter instance
_exporter: Optional[ReportExporter] = None


def get_exporter() -> ReportExporter:
    """Get or create global exporter"""
    global _exporter
    if _exporter is None:
        _exporter = ReportExporter()
    return _exporter